#!/bin/bash - 
#
#          FILE: change_wallpapers.sh
#         USAGE: ./change_wallpapers.sh 
#        AUTHOR: Apacal (), apacal@126.com
#       CREATED: 2015年01月06日 12:25


DIR=/usr/local/wallpapers/picture/

if [ "$1" = "now" ]; then
    FILECOUNT=$(echo $DIR*.* | wc -w)
    RAND=$(shuf -i 1-$FILECOUNT -n 1)
    INC=1
    for i in $(echo $DIR*.*); do
        if [ $INC -eq $RAND ]; then
            echo $i
            gsettings set org.gnome.desktop.background picture-uri file:///${i}
            if [ $? -eq 0 ]; then
                echo "success!"
            fi
            break
        fi
        INC=$(($INC + 1))
    done

else

    image=`/usr/local/wallpapers/bin/getwallpapers`
    image="/usr/local/wallpapers/picture/$image"
    if [ -f $image ]; then
        gsettings set org.gnome.desktop.background picture-uri "file:///$image"
        if [ $? -eq 0 ]; then
            echo $image
            echo "success!"
        fi
    else
        tail /usr/local/wallpapers/log/error_log
        echo "image is invalid"
    fi
fi




